config/routes.rb
Rails.application.routes.draw do
  resources :rents
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :searches
  resources :microposts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # root 'static_pages#home'
  root 'microposts#index'
  get  '/home',    to: 'microposts#index', as: 'helf'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/postnew', to: 'microposts#new'
  get  '/usershow', to: 'users#show'

  get  '/signup', to: 'users#new'
  get    '/login',   to: 'session#new'
  get    '/activation',   to: 'account_activations#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token, :reset_token
    has_many :microposts
    before_save :downcase_email
    before_create :create_activation_digest
    validates :name, length: {maximum: 15}
    validates:email,
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },
    uniqueness: { case_sensitive: false }
    has_secure_password
    validates:password, presence: true, length:{minimum: 6}
# Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

     # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token =  User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end
        # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
    #   forgets a user
      def forget
        update_attribute(:remember_digest,nil)
      end
      def downcase_email 
         self.email = email.downcase 
      end
      def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
        
      end
      # Activates an account.
  def activate
    update_columns(activated: FILL_IN, activated_at: FILL_IN)
  end
      # Sends activation email.
      def send_activation_email
        UserMailer.account_activation(self).deliver_now
      end

      def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest,  User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
      end
      def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  attr_accessor :name, :email
  def index
    @users = User.where(activated: FILL_IN).paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    redirect_to root_url
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        @user.send_activation_email
        flash[:info] = "Please check your email to activate your account."
        # flash[:success] = "Welcome to the Sample App!"
        UserMailer.account_activation(@user).deliver_now
        redirect_to root_url
      else
      render 'new'
      end
    end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
      # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password , class: 'form-control'%>
  </div>
  <div class="field">
    <%= form.label :password_confirmation,"Confirmation" %>
    <%= form.password_field :password_confirmation , class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create Account</h1>


<%= render 'shared/error_messages' %>
<%= render 'form', user: @user %>

<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= gravatar_for @user %>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>