config/routes.rb
Rails.application.routes.draw do
  resources :rents
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :searches
  resources :microposts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # root 'static_pages#home'
  root 'microposts#index'
  get  '/home',    to: 'microposts#index', as: 'helf'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/postnew', to: 'microposts#new'
  get  '/usershow', to: 'users#show'

  get  '/signup', to: 'users#new'
  get    '/login',   to: 'session#new'
  get    '/activation',   to: 'account_activations#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rent.rb
class Rent < ApplicationRecord
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]

  # GET /rents
  # GET /rents.json
  def index
    @rents = Rent.all
  end

  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    @rent = Rent.new
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new(rent_params)

    respond_to do |format|
      if @rent.save
        format.html { redirect_to @rent, notice: 'Rent was successfully created.' }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_params
      params.require(:rent).permit(:tel, :fullname, :address, :user_id, :micropost_id)
    end
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<%= form_with(model: rent, local: true) do |form| %>
  <% if rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel %>
  </div>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :micropost_id %>
    <%= form.number_field :micropost_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rents/edit.html.erb
<h1>Editing Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

app/views/rents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rents</h1>

<table>
  <thead>
    <tr>
      <th>Tel</th>
      <th>Fullname</th>
      <th>Address</th>
      <th>User</th>
      <th>Micropost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.tel %></td>
        <td><%= rent.fullname %></td>
        <td><%= rent.address %></td>
        <td><%= rent.user_id %></td>
        <td><%= rent.micropost_id %></td>
        <td><%= link_to 'Show', rent %></td>
        <td><%= link_to 'Edit', edit_rent_path(rent) %></td>
        <td><%= link_to 'Destroy', rent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rent', new_rent_path %>

app/views/rents/new.html.erb
<h1>New Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Back', rents_path %>

app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tel:</strong>
  <%= @rent.tel %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @rent.fullname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @rent.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @rent.user_id %>
</p>

<p>
  <strong>Micropost:</strong>
  <%= @rent.micropost_id %>
</p>

<%= link_to 'Edit', edit_rent_path(@rent) %> |
<%= link_to 'Back', rents_path %>